### ISSUE TITLE
DSE

### ISSUE THREAD

**Issue by devilineyes2** [hfiref0x/KDU#23]
What happens I don't set dse 0 and dse 6 after mapping the driver?

**Comment by hfiref0x** [comment]
Nothing. Manually mapped drivers and DSE are unrelated because manual mapping doesn't rely on Windows kernel loader. Setting DSE flags to 0 will turn off all possible code integrity options so you will be able to load normally any unsigned driver, or driver with a revoked/expired certificate. Setting DSE to any other value except 0 will turn on some code integrity options. Value of "6" is not a magic value, it is a combination of various flags, depending on Windows versions and settings these flags can be different, "6" is just an example.

**Comment by devilineyes2** [comment]
So if I'm using kdu.exe -map testdriver.sys for mapping my driver, setting dse 0 is not required, right?

**Comment by devilineyes2** [comment]
Also, is it normal to get NalDrv.sys bsod SYSTEM_SERVICE_EXCEPTION while loading on Windows 11? I don't have the dump file cause I immediately switched into Windows 10.

**Comment by hfiref0x** [comment]
> So if I'm using kdu.exe -map testdriver.sys for mapping my driver, setting dse 0 is not required, right?

yes

> Also, is it normal to get NalDrv.sys bsod SYSTEM_SERVICE_EXCEPTION while loading on Windows 11? I don't have the dump file cause I immediately switched into Windows 10.

all these drivers used by kdu are vulnerable and bugged, no one guarantee you that they will work anywhere. If Intel doesn't work then use different provider by specifying "-prv id" switch, id you can take from table in the readme. Intel is default and has id 0.

**Comment by devilineyes2** [comment]
Thanks a lot for honest answer.
