### ISSUE TITLE
BSOD

### ISSUE THREAD

**Issue by Camiao64** [hfiref0x/KDU#70]
After using -dse 6 and -map Driver.sys my pc would BSOD after a while (sometimes very soon sometimes takes a bit) with the error CRITICAL_STRUCTURE_CORRUPTION on CI.dll 

any idea for a fix? i see that Ci dll is loaded by kdu so im guessing thats where the issue originated from

![image](https://github.com/hfiref0x/KDU/assets/121247685/8ac9caae-afd5-4e9a-a42f-741456533a33)
minidump file below

[082323-9531-01.zip](https://github.com/hfiref0x/KDU/files/12418578/082323-9531-01.zip)

**Comment by hfiref0x** [comment]
Do you know about PatchGuard?

**Comment by Camiao64** [comment]
nope I just updated windows to 22H2 so it's prob came from there. any way to get around or disable it?Sent from my phone-------- Original message --------From: hfiref0x ***@***.***>Date: Wed, 23 Aug 2023, 11:35 pmTo: hfiref0x/KDU ***@***.***>Cc: Camiao64 ***@***.***>, Author ***@***.***>Subject: Re: [hfiref0x/KDU] BSOD (Issue #70)
Do you know about PatchGuard?

**Comment by hfiref0x** [comment]
No it is there since ages. It seems you are unfamiliar with what you do. You can google PatchGuard and your bugcheck code. Nothing from what you posted are issues of KDU. Using this tool expects from you that you understand what you do and familiar with Windows NT internals at least at beginner level.

I'm not providing educational tutorials here, so I'm sorry but I will close this issue as unrelated.
